=== halc8312/custom-app-2/sakura-ken/residents/certificates/residence-certificate-template.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "桜県住民票テンプレート",
  "description": "住民票の写し交付用テンプレート",
  "type": "object",
  "properties": {
    "certificate_info": {
      "type": "object",
      "properties": {
        "certificate_number": {
          "type": "string",
          "description": "証明書番号"
        },
        "issue_date": {
          "type": "string",
          "format": "date",
          "description": "交付日"
        },
        "issuing_office": {
          "type": "string",
          "description": "交付機関"
        },
        "issuing_officer": {
          "type": "string",
          "description": "交付担当者"
        },
        "certificate_type": {
          "type": "string",
          "enum": ["住民票の写し", "住民票記載事項証明書", "除票"],
          "description": "証明書種別"
        }
      }
    },
    "resident_info": {
      "type": "object",
      "properties": {
        "氏名": {
          "type": "string"
        },
        "通称": {
          "type": "string",
          "description": "外国人住民の場合"
        },
        "生年月日": {
          "type": "string"
        },
        "性別": {
          "type": "string"
        },
        "住所": {
          "type": "object",
          "properties": {
            "現住所": {
              "type": "string"
            },
            "方書": {
              "type": "string",
              "description": "建物名・部屋番号等"
            }
          }
        },
        "住民となった日": {
          "type": "string",
          "format": "date"
        },
        "住所を定めた日": {
          "type": "string",
          "format": "date"
        },
        "前住所": {
          "type": "string"
        },
        "転出予定地": {
          "type": "string",
          "description": "転出届が出されている場合"
        },
        "世帯主": {
          "type": "object",
          "properties": {
            "氏名": {
              "type": "string"
            },
            "続柄": {
              "type": "string"
            }
          }
        },
        "本籍": {
          "type": "string",
          "description": "日本人住民の場合"
        },
        "筆頭者": {
          "type": "string",
          "description": "日本人住民の場合"
        },
        "国籍・地域": {
          "type": "string",
          "description": "外国人住民の場合"
        },
        "在留資格": {
          "type": "string",
          "description": "外国人住民の場合"
        },
        "在留期間": {
          "type": "string",
          "description": "外国人住民の場合"
        },
        "住民票コード": {
          "type": "string",
          "description": "11桁の番号"
        },
        "個人番号": {
          "type": "string",
          "description": "マイナンバー（要請があった場合のみ記載）"
        }
      }
    },
    "household_info": {
      "type": "object",
      "properties": {
        "世帯構成員": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "氏名": {
                "type": "string"
              },
              "続柄": {
                "type": "string"
              },
              "生年月日": {
                "type": "string"
              },
              "性別": {
                "type": "string"
              }
            }
          },
          "description": "世帯全員の住民票の場合"
        }
      }
    },
    "additional_info": {
      "type": "object",
      "properties": {
        "備考": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "その他の記載事項"
        },
        "履歴": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "日付": {
                "type": "string",
                "format": "date"
              },
              "事由": {
                "type": "string"
              },
              "詳細": {
                "type": "string"
              }
            }
          },
          "description": "住所変更履歴等"
        }
      }
    },
    "certification": {
      "type": "object",
      "properties": {
        "認証文": {
          "type": "string",
          "default": "上記のとおり相違ないことを証明する。"
        },
        "発行者": {
          "type": "object",
          "properties": {
            "役職": {
              "type": "string",
              "default": "桜県○○市長"
            },
            "氏名": {
              "type": "string"
            },
            "印章": {
              "type": "string",
              "description": "電子印章ID"
            }
          }
        }
      }
    },
    "usage_info": {
      "type": "object",
      "properties": {
        "有効期限": {
          "type": "string",
          "default": "発行日から3ヶ月"
        },
        "使用目的": {
          "type": "string"
        },
        "提出先": {
          "type": "string"
        }
      }
    }
  }
}

=== halc8312/custom-app-2/sakura-ken/residents/certificates/samples/residence-certificate-sakurada.json
{
  "certificate_info": {
    "certificate_number": "桜花住証第2025-00001号",
    "issue_date": "2025-01-13",
    "issuing_office": "桜花市役所市民課",
    "issuing_officer": "窓口担当：田中",
    "certificate_type": "住民票の写し"
  },
  "resident_info": {
    "氏名": "桜田 一郎",
    "生年月日": "昭和53年3月15日",
    "性別": "男",
    "住所": {
      "現住所": "桜県桜花市中央地区1丁目1番1号",
      "方書": ""
    },
    "住民となった日": "平成20年10月15日",
    "住所を定めた日": "平成20年10月15日",
    "前住所": "桜県桜花市東地区3丁目4番5号",
    "世帯主": {
      "氏名": "桜田 一郎",
      "続柄": "本人"
    },
    "本籍": "桜県桜花市中央地区1丁目1番1号",
    "筆頭者": "桜田 一郎",
    "住民票コード": "28010000010"
  },
  "household_info": {
    "世帯構成員": [
      {
        "氏名": "桜田 一郎",
        "続柄": "世帯主",
        "生年月日": "昭和53年3月15日",
        "性別": "男"
      },
      {
        "氏名": "桜田 花子",
        "続柄": "妻",
        "生年月日": "昭和55年7月22日",
        "性別": "女"
      },
      {
        "氏名": "桜田 太郎",
        "続柄": "子",
        "生年月日": "平成22年9月5日",
        "性別": "男"
      },
      {
        "氏名": "桜田 美咲",
        "続柄": "子",
        "生年月日": "平成25年4月12日",
        "性別": "女"
      }
    ]
  },
  "additional_info": {
    "備考": [
      "平成20年10月15日 婚姻により東地区より転居",
      "令和2年4月1日 住居表示実施"
    ],
    "履歴": [
      {
        "日付": "2000-04-01",
        "事由": "転居",
        "詳細": "桜花市西地区より東地区へ転居"
      },
      {
        "日付": "2008-10-15",
        "事由": "転居",
        "詳細": "婚姻により東地区より中央地区へ転居"
      }
    ]
  },
  "certification": {
    "認証文": "上記のとおり相違ないことを証明する。",
    "発行者": {
      "役職": "桜県桜花市長",
      "氏名": "山本 太郎",
      "印章": "桜花市長之印"
    }
  },
  "usage_info": {
    "有効期限": "発行日から3ヶ月",
    "使用目的": "運転免許証更新",
    "提出先": "桜県警察本部運転免許センター"
  }
}
